################################# Default configuration ###################
baseURL = "/fr"
title = "École de karaté Candiac"
theme = "karate-candiac-hugo"
themesDir = "../.."
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []
defaultContentLanguage = "fr"

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700|Montserrat&display=swap"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;500&family=Roboto:ital,wght@0,400;0,500;0,700;1,700&display=swap"
[[params.plugins.css]]
link = "karateSite/static/css/style.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "Schedule"
pre = "en/#"
url = "services"
weight = 1

[[Languages.en.menu.main]]
name = "Registration"
pre = "en/#"
url = "cta"
weight = 2

[[Languages.en.menu.main]]
name = "Our Team"
pre = "en/#"
url = "portfolio"
weight = 3

[[Languages.en.menu.main]]
name = "Styles and Techniques"
pre = "en/#"
url = "team"
weight = 4

[[Languages.en.menu.main]]
name = "Contact Us"
pre = "en/#"
url = "pricing"
weight = 5

################### French Navigation ########################

[[Languages.fr.menu.main]]
name = "Horaire"
pre = "#"
url = "services"
weight = 1


[[Languages.fr.menu.main]]
name = "Inscriptions"
pre = "#"
url = "cta"
weight = 2

[[Languages.fr.menu.main]]
name = "Équipe"
pre = "#"
url = "team"
weight = 3

[[Languages.fr.menu.main]]
name = "Style et techniques"
pre = "#"
url = "blog"
weight = 4

[[Languages.fr.menu.main]]
name = "contact"
pre = "#"
url = "contact"
weight = 7


############################# Default Parameters ##########################
[params]

logo = "images/logo.png"
# Meta data
description = "École de karaté Candiac"
author = "Themefisher"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = false

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = true
map_latitude = "45.378518,"
map_longitude = "-73.5103279"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/profile.php?id=100054426583000"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UCqJ0vAr2dNees3X8OG0x5qw"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
copyright = "Copyright &copy; 2024"

################################ France Language ########################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-ca"
contentDir = "content/french"
weight = 1
home = "Accueil"
copyright = "Copyright &copy; 2024"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
